[workspace]

members = [
    "mem6_common",
    "mem6",
    "mem6_server",
]

# Rust does not have yet 2020-04-20 profiles on webspave projects
# I can put it only on the workspace alone.
[profile.release]
panic = "abort"